@baseUrl = http://localhost:3000

@jwtToken = {{authLogin.response.body.accessToken}}

### Auth login
# @name authLogin
POST {{baseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "leo@email.com",
  "password": "leo123"
}

### Read One user
# @name readOneUser
GET {{baseUrl}}/user/1
Authorization: Bearer {{jwtToken}}

### Create user
# @name createUser
POST {{baseUrl}}/user
Content-Type: application/json
Accept: application/json

{
  "name": "João",
  "email": "joao@email.com",
  "password": "123456"
}

### Update user
# @name createUser
PATCH  {{baseUrl}}/user/me
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwtToken}}

{
  "name": "Leonardo",
  "email": "leo@email.com"
}

### Update user password
# @name updateUserPassword
PATCH  {{baseUrl}}/user/me/password
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwtToken}}

{
  "currentPassword": "leo123",
  "newPassword": "leo123"
}
